<div>
<h1>Rules for authors</h1>
The journal "Oncology and Radiology of Kazakhstan" accepts for publication articles on the organization of cancer services, cancer epidemiology, experimental oncology and radiobiology, diagnosis of precancerous and cancer, issues of Clinical Oncology, the standards of diagnosis and treatment. Can be presented methodological developments, results of research, lectures, literary reviews, individual case studies. <p/><p/>
1. The article should be accompanied by the direction of the institution in which this work is carried out, and the head of a visa.<p/>
2. The article should be printed on one side of a sheet 1.5 line spacing. The editors provide two copies of the manuscript (paper size A4). Be sure to provide material in electronic form (text editor Word 7,0 or a higher version, in the format .doc. Or docx. Font Times New Roman Cyr, font entire article -14 abstract - 12).<p/>
3. The order of the text in the article on page 1 in the upper left corner indicated in italics UDC, below - in the middle initials (name) and last name of the author (s) on the next line in the center - the place of the authors (full name of the department, Department of the institution from which the article is based) on the next line in the center of capital letters in the usual bold - the article title on the next line on the width of the page in italics - the summary in the language of the article, followed by an additional 1 interval - the text of the article, then - a list of references, summaries in other languages. At the end of the article should be first name, middle name (in full) of the author(s), address, zip code, phone number, e-mail, handwritten signature. Collective article should be signed by all authors.<p/>
4. The paper, revealing the original investigation, should not exceed 8 pages of typescript, Anecdotal reports - 4 pages, reviews of the literature and lectures -12 pages. The editors reserve the right to shorten articles.<p/>
5. The structure of the article.<p/>
- "Introduction" should be brief and orient the reader to the urgency of the problem and the purpose of the research problem. It should refer to the most important work without a detailed review of the literature.<p/>
- In the "Materials and methods" should be submitted to the principles of selection and characterization of the material, the scope of the study, the methods used, including statistics. Research methods should be presented briefly, but clearly enough to be able to play them.<p/>
- Section "The results of the study" should contain the data. This section may be combined with the following<p/>
- In the "Discussion" personal data must be compared with similar reports in the domestic and foreign literature, drew attention to the originality of the study, the presence of new proposals, etc.<p/>
- In the "References" bibliographic references must be numbered in the order mentioned in the text of the manuscript (in the text are given in brackets). In the literature list:<p/>
- For the books - the initials and surname of the author, full title, place and year of publication, pages "from" and "to";<p/>
- For journal articles - the initials and surname of the author, full title, journal name, year, volume, number, pages "from" and "to";<p/>
- The reduction of words and names other than common abbreviations measures, physical, mathematical quantities and terms shall be permitted only with the initial indication of the full name.<p/>
- Abstract in Russian, Kazakh (Tұzhyrym) and English (Summary) languages with the location of the author (s), IOF authors, title of the article and have the following sections: the relevance, purpose of the study, material and methods, including statistics, the main results, Finally, keywords. Abstract should be 1/2 page with a headline. Abstract in the language of the article is placed before the main text of the article, annotations in other languages - at the end.<p/>
6. References to tables and figures are given in the text in a word with the number (Table 1, Figure 1) in parentheses. Tables should be placed with one extra padding before and after the text. These are printed through 1 interval<p/>
Articles should not be overwhelmed by the illustrative material. Photos, drawings, graphics and diagrams can be presented in the form of contrasting pictures or graphs (or editors Word 7,0, Excel 7,0), readable in black and white. At the location of illustrations in the text, to left field put the article indication that the illustrations and their name. Drawings of all inserted into the Word with a single indentation before and after the text in the center, signature bottom center. The editors reserve the right to the original layout of materials and change the format of the accompanying illustrations.<p/>
7. The author is responsible for the correctness of the data presented in the attached list of literature, which included only those publications that are specified in the text. References must be typed on a separate sheet of typewriting through 1.5 intervals. The list includes the works of local and foreign authors in the past 10 years. Only if necessary allowed references to individual earlier work. It is advisable to quote no more than 10-20 sources.<p/>
8. Articles that do not meet the requirements for publication are not allowed, as the author shall be notified.<p/>
9. The accuracy of promotional materials revision is not responsible.<p/>
10. Payment for the article produced at the rate of {$sumPerPage} tenge per 1 page.<p/>
<p/>
<p><a href="files/instruction.pdf" download>Download rules for authors</a>
</div>
