UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Анестезиология, реаниматология', name_rus = 'Анестезиология, реаниматология', name_eng = 'Anesthesiology, Resuscitation' WHERE id = 1;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Практикалық дәрігерге көмек', name_rus = 'В помощь практическому врачу', name_eng = 'For the Practicing Physician' WHERE id = 2;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Диагностика мәселелері', name_rus = 'Вопросы диагностики', name_eng = 'Diagnostic Issues' WHERE id = 3;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Диагностика', name_rus = 'Диагностика', name_eng = 'Diagnostics' WHERE id = 4;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Иммунология', name_rus = 'Иммунология', name_eng = 'Immunology' WHERE id = 5;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Сұхбат', name_rus = 'Интервью', name_eng = 'Interview' WHERE id = 6;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Канцерогенез', name_rus = 'Канцерогенез', name_eng = 'Carcinogenesis' WHERE id = 7;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Клиникалық фармакология', name_rus = 'Клиническая фармакология', name_eng = 'Clinical Pharmacology' WHERE id = 8;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкология бойынша клиникалық зерттеулер', name_rus = 'Клинические исследования по онкологии', name_eng = 'Clinical Oncology Research' WHERE id = 9;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Радиология бойынша клиникалық зерттеулер', name_rus = 'Клинические исследования по радиологии', name_eng = 'Clinical Radiology Research' WHERE id = 10;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Консервативті емдеу', name_rus = 'Консервативное лечение', name_eng = 'Conservative Treatment' WHERE id = 11;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Конференция', name_rus = 'Конференция', name_eng = 'Conference' WHERE id = 12;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Дәрі-дәрмек терапиясы', name_rus = 'Лекарственная терапия', name_eng = 'Drug Therapy' WHERE id = 13;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Лекциялар', name_rus = 'Лекции', name_eng = 'Lectures' WHERE id = 14;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Емдеу', name_rus = 'Лечение', name_eng = 'Treatment' WHERE id = 15;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Сәулелік терапия', name_rus = 'Лучевая терапия', name_eng = 'Radiation Therapy' WHERE id = 16;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Мастер-класс', name_rus = 'Мастер-класс', name_eng = 'Master Class' WHERE id = 17;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Анализ әдістері', name_rus = 'Методы анализа', name_eng = 'Analysis Methods' WHERE id = 19;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Молекулалық медицина', name_rus = 'Молекулярная медицина', name_eng = 'Molecular Medicine' WHERE id = 20;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкологиядағы жаңалықтар', name_rus = 'Новое в онкологии', name_eng = 'Oncology News' WHERE id = 21;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Жаңа технологиялар', name_rus = 'Новые технологии', name_eng = 'New Technologies' WHERE id = 22;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Әдеби шолу', name_rus = 'Обзор литературы', name_eng = 'Literature Review' WHERE id = 23;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Шолулар', name_rus = 'Обзоры', name_eng = 'Reviews' WHERE id = 24;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкогинекология', name_rus = 'Онкогинекология', name_eng = 'Oncogynecology' WHERE id = 25;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкологиялық эпидемиология', name_rus = 'Онкологическая эпидемиология', name_eng = 'Oncological Epidemiology' WHERE id = 26;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкопсихология', name_rus = 'Онкопсихология', name_eng = 'Oncopsychology' WHERE id = 27;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкохирургия', name_rus = 'Онкохирургия', name_eng = 'Oncosurgery' WHERE id = 28;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкологиялық мекемелер тәжірибесі', name_rus = 'Опыт работы онкологических учреждений', name_eng = 'Experience of Oncology Institutions' WHERE id = 29;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Денсаулық сақтауды ұйымдастыру', name_rus = 'Организация здравоохранения', name_eng = 'Healthcare Organization' WHERE id = 30;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Онкологиялық қызметті ұйымдастыру', name_rus = 'Организация онкологической службы', name_eng = 'Organization of Oncology Service' WHERE id = 31;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Түпнұсқа мақалалар', name_rus = 'Оригинальные статьи', name_eng = 'Original Articles' WHERE id = 33;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Әріптестерге арналған еске алу', name_rus = 'Памяти коллег', name_eng = 'In Memory of Colleagues' WHERE id = 34;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Кезеңдік зиянды ісік диагностикасы мен емдеу хаттамалары', name_rus = 'Периодические протоколы диагностики и лечения злокачественных опухолей', name_eng = 'Periodic Protocols for Malignant Tumor Diagnosis and Treatment' WHERE id = 35;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Диагностика және емдеу хаттамалары', name_rus = 'Протоколы диагностики и лечения', name_eng = 'Diagnostic and Treatment Protocols' WHERE id = 36;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Психотерапия', name_rus = 'Психотерапия', name_eng = 'Psychotherapy' WHERE id = 37;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Практикалық дәрігерлер жарияланымдары', name_rus = 'Публикации практических врачей', name_eng = 'Publications of Practical Physicians' WHERE id = 38;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Әртүрлі', name_rus = 'Разное', name_eng = 'Miscellaneous' WHERE id = 39;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Мейіргер ісі', name_rus = 'Сестринское дело', name_eng = 'Nursing' WHERE id = 40;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Скрининг', name_rus = 'Скрининг', name_eng = 'Screening' WHERE id = 41;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Клиникалық тәжірибеден жағдай', name_rus = 'Случай из практики', name_eng = 'Case from Practice' WHERE id = 42;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Статистика', name_rus = 'Статистика', name_eng = 'Statistics' WHERE id = 43;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Мақалалар', name_rus = 'Статьи', name_eng = 'Articles' WHERE id = 44;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Тезистер', name_rus = 'Тезисы', name_eng = 'Abstracts' WHERE id = 45;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Конференция тезистері', name_rus = 'Тезисы конференции', name_eng = 'Conference Abstracts' WHERE id = 46;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Қазақстан Республикасының ғалымдары', name_rus = 'Ученые Республики  Казахстан', name_eng = 'Scientists of the Republic of Kazakhstan' WHERE id = 47;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Химиотерапия', name_rus = 'Химиотерапия', name_eng = 'Chemotherapy' WHERE id = 48;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Химиотерапия, сәулелік терапия', name_rus = 'Химиотерапия, лучевая терапия', name_eng = 'Chemotherapy, Radiation Therapy' WHERE id = 49;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Хирургиялық емдеу', name_rus = 'Хирургическое лечение', name_eng = 'Surgical Treatment' WHERE id = 50;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Хроника. Мастер-класстар', name_rus = 'Хроника. Мастер-классы', name_eng = 'Chronicle. Master Classes' WHERE id = 51;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Эксперименталды онкология', name_rus = 'Экспериментальная онкология', name_eng = 'Experimental Oncology' WHERE id = 52;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Эпидемиология', name_rus = 'Эпидемиология', name_eng = 'Epidemiology' WHERE id = 53;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Юбилейлер', name_rus = 'Юбилеи', name_eng = 'Anniversaries' WHERE id = 54;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Профилактика', name_rus = 'Профилактика', name_eng = 'Prevention' WHERE id = 55;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Кадрларды даярлау', name_rus = 'Подготовка кадров', name_eng = 'Personnel Training' WHERE id = 56;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Паллиативтік көмек', name_rus = 'Паллиативная помощь', name_eng = 'Palliative Care' WHERE id = 57;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Басы мен мойнының қатерлі ісіктері', name_rus = 'Злокачественные опухоли головы и шеи', name_eng = 'Malignant Tumors of Head and Neck' WHERE id = 58;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Маммология', name_rus = 'Маммология', name_eng = 'Mammology' WHERE id = 59;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Сүт безі рагы', name_rus = 'Рак молочной железы', name_eng = 'Breast Cancer' WHERE id = 60;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Бауыр рагы', name_rus = 'Рак печени', name_eng = 'Liver Cancer' WHERE id = 61;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Өкпе рагы', name_rus = 'Рак легкого', name_eng = 'Lung Cancer' WHERE id = 62;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Тік ішек рагы', name_rus = 'Рак прямой кишки', name_eng = 'Rectal Cancer' WHERE id = 63;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Көптелген миелома', name_rus = 'Множественная миелома', name_eng = 'Multiple Myeloma' WHERE id = 64;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Меланома', name_rus = 'Меланома', name_eng = 'Melanoma' WHERE id = 65;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'KazNIIOiR ардагерлері мен қызметкерлері марапатталды', name_rus = 'Награждены ветераны и сотрудники КазНИИОиР', name_eng = 'Awarded Veterans and Employees of KazNIIOiR' WHERE id = 66;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Асқазан рагы', name_rus = 'Рак желудка', name_eng = 'Stomach Cancer' WHERE id = 67;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Ұйқы безі рагы', name_rus = 'Рак поджелудочной железы', name_eng = 'Pancreatic Cancer' WHERE id = 68;
UPDATE `p-5080_bibl_publication`.bibl_section SET name_kaz = 'Өңеш рагы', name_rus = 'Рак пищевода', name_eng = 'Esophageal Cancer' WHERE id = 69;